<a href="https://colab.research.google.com/github/Jyothi-Swaroop5/CodeAlpha/blob/main/Week2/Pandas/pandastest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
s=pd.Series([1,2,3,4,5])
s

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
s.name='numbers'
s

0    1
1    2
2    3
3    4
4    5
Name: numbers, dtype: int64

In [ ]:
s[1:4]

1    2
2    3
3    4
Name: numbers, dtype: int64

In [ ]:
s.iloc[[2,3,4]]

2    3
3    4
4    5
Name: numbers, dtype: int64

In [ ]:
s[[0,1,2]]

0    1
1    2
2    3
Name: numbers, dtype: int64

In [ ]:
list=['a','b','c','d','e']
s.index=list
s

a    1
b    2
c    3
d    4
e    5
Name: numbers, dtype: int64

In [ ]:
s.loc['c']

np.int64(3)

In [ ]:
s.values

array([1, 2, 3, 4, 5])

In [ ]:
d={'a':1,'b':2,'c':3}
d

{'a': 1, 'b': 2, 'c': 3}

In [ ]:
ss=pd.Series(d)
ss

a    1
b    2
c    3
dtype: int64

In [ ]:
ss.name='n'

In [ ]:
print(ss>2)

a    False
b    False
c     True
Name: n, dtype: bool

In [ ]:
print(ss[(s>0.5) & (s<2)])

a    1
Name: n, dtype: int64

In [ ]:
ss['b']=33
ss

a     1
b    33
c     3
Name: n, dtype: int64

In [ ]:
import numpy as np
ser=pd.Series(['a',np.nan,1,np.nan,6])
ser.notnull().sum()

np.int64(3)

In [ ]:
data={
    "name":['a','b','c','d','e'],
    "age":[1,2,3,np.nan,5],
    "Dep":['ds','ai','aiml',np.nan,'ece'],
    "sal":[2354,456,234,456,234]
}
data

{'name': ['a', 'b', 'c', 'd', 'e'],
 'age': [1, 2, 3, nan, 5],
 'Dep': ['ds', 'ai', 'aiml', nan, 'ece'],
 'sal': [2354, 456, 234, 456, 234]}

In [ ]:
df=pd.DataFrame(data)
df

  name  age   Dep   sal
0    a  1.0    ds  2354
1    b  2.0    ai   456
2    c  3.0  aiml   234
3    d  NaN   NaN   456
4    e  5.0   ece   234

In [ ]:
df.head(2)

  name  age Dep   sal
0    a  1.0  ds  2354
1    b  2.0  ai   456

In [ ]:
df.tail()

  name  age   Dep   sal
0    a  1.0    ds  2354
1    b  2.0    ai   456
2    c  3.0  aiml   234
3    d  NaN   NaN   456
4    e  5.0   ece   234

In [ ]:
df.loc[1:3,['age','sal']]

   age  sal
1  2.0  456
2  3.0  234
3  NaN  456

In [ ]:
df.shape

(5, 4)

In [ ]:
print(df.shape)

(5, 4)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    5 non-null      object
 1   age     4 non-null      float64
 2   Dep     4 non-null      object
 3   sal     5 non-null      int64
dtypes: float64(1), int64(1), object(2)
memory usage: 292.0+ bytes

In [ ]:
df.describe()

            age          sal
count  4.000000     5.000000
mean   2.750000   746.800000
std    1.707825   905.282939
min    1.000000   234.000000
25%    1.750000   234.000000
50%    2.500000   456.000000
75%    3.500000   456.000000
max    5.000000  2354.000000

In [ ]:
df['sal']=df['sal']+2000
df['sal']

0    4354
1    2456
2    2234
3    2456
4    2234
Name: sal, dtype: int64

In [ ]:
print(df.rename(columns={'Dep':'dept'},inplace=True))

None

In [ ]:
df

  name  age  dept   sal
0    a  1.0    ds  4354
1    b  2.0    ai  2456
2    c  3.0  aiml  2234
3    d  NaN   NaN  2456
4    e  5.0   ece  2234

In [ ]:
df['psal']=df['sal']+333
df

  name  age  dept   sal  psal
0    a  1.0    ds  4354  4687
1    b  2.0    ai  2456  2789
2    c  3.0  aiml  2234  2567
3    d  NaN   NaN  2456  2789
4    e  5.0   ece  2234  2567

In [ ]:
df.isnull().sum()

name    0
age     1
dept    1
sal     0
psal    0
dtype: int64

In [ ]:
df

  name  age  dept   sal  psal
0    a  1.0    ds  4354  4687
1    b  2.0    ai  2456  2789
2    c  3.0  aiml  2234  2567
3    d  NaN   NaN  2456  2789
4    e  5.0   ece  2234  2567

In [ ]:
df.dropna(how='all')

  name  age  dept   sal  psal
0    a  1.0    ds  4354  4687
1    b  2.0    ai  2456  2789
2    c  3.0  aiml  2234  2567
3    d  NaN   NaN  2456  2789
4    e  5.0   ece  2234  2567

In [ ]:
df.fillna(0)

  name  age  dept   sal  psal
0    a  1.0    ds  4354  4687
1    b  2.0    ai  2456  2789
2    c  3.0  aiml  2234  2567
3    d  0.0     0  2456  2789
4    e  5.0   ece  2234  2567

In [ ]:
df['age'].fillna(df['age'].mean())

0    1.00
1    2.00
2    3.00
3    2.75
4    5.00
Name: age, dtype: float64

In [ ]:
df

  name  age  dept   sal  psal
0    a  1.0    ds  4354  4687
1    b  2.0    ai  2456  2789
2    c  3.0  aiml  2234  2567
3    d  NaN   NaN  2456  2789
4    e  5.0   ece  2234  2567

In [ ]:
df.drop(columns=5,inplace=True)

KeyError: '[5] not found in axis'

In [ ]:
df

In [ ]:
df.drop(6,inplace=True)
df

In [ ]:
df.loc[len(df)]=['f',np.nan,'cse',3454,4564]

In [ ]:
df

In [ ]:
df['age'].fillna(method='bfill')

In [ ]:
df

In [ ]:
df['name'].replace('c','cc')

In [ ]:
df

In [ ]:
df['name']=df['name'].replace('c','f')

In [ ]:
df

In [ ]:
df.loc[6]=['a',1,'ds',4354,4687]

In [ ]:
df

In [ ]:
df[df.duplicated()]

In [ ]:
df.drop_duplicates()

In [ ]:
df['psal']=df['psal'].apply(lambda x:x/10 if x> 3455 else x )

In [ ]:
df

In [ ]:
df=df.drop_duplicates()

In [ ]:
df

In [ ]:
df['age']=df['age'].fillna(df['age'].mean())

In [ ]:
df

In [ ]:
df['name']=df['name'].replace('c_f','c_f_e')

In [ ]:
df

In [ ]:
df[['first_name','last_name']]=df['name'].str.split('_',n=1, expand=True)
df

ValueError: Columns must be same length as key

In [ ]:
df

  name  age  dept   sal  psal
0    a  1.0    ds  4354  4687
1    b  2.0    ai  2456  2789
2    c  3.0  aiml  2234  2567
3    d  NaN   NaN  2456  2789
4    e  5.0   ece  2234  2567

In [ ]:
df['age']=df['age'].fillna(df['age'].median())

In [ ]:
df

  name  age  dept   sal  psal
0    a  1.0    ds  4354  4687
1    b  2.0    ai  2456  2789
2    c  3.0  aiml  2234  2567
3    d  2.5   NaN  2456  2789
4    e  5.0   ece  2234  2567

In [ ]:
df['age']=df['age'].apply(lambda x:x*10)

In [ ]:
df

  name   age  dept   sal  psal
0    a  10.0    ds  4354  4687
1    b  20.0    ai  2456  2789
2    c  30.0  aiml  2234  2567
3    d  25.0   NaN  2456  2789
4    e  50.0   ece  2234  2567

In [ ]:
import pandas as pd

# DataFrame 1
df1 = pd.DataFrame({
    'emp_id': [101, 102, 103, 104],
    'name': ['Ram', 'Sam', 'John', 'David'],
    'dept_id': [1, 2, 1, 3]
})

# DataFrame 2
df2 = pd.DataFrame({
    'dept_id': [1, 2, 3, 4],
    'department': ['HR', 'IT', 'Finance', 'Marketing']
})

print(df1)
print()
print(df2)
pd.concat([df1,df2])
pd.concat([df1,df2],axis=1)
pd.merge(df1,df2,on='dept_id')