<a href="https://colab.research.google.com/github/Jyothi-Swaroop5/CodeAlpha/blob/main/Week2/Pandas/pdlast.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
data = {
    "Order_ID": [2001, 2002, 2003, 2004, 2005,
                 2006, 2007, 2008, 2009, 2010,
                 2011, 2012, 2013, 2014, 2015,
                 2016, 2017, 2018, 2019, 2020],

    "Customer_Name": ["Ravi", "Anu", "Kiran", "Meena", "John",
                      "Priya", "Aman", "Sita", "Rahul", "David",
                      "Pooja", "Arjun", "Kavya", "Mohan", "Neha",
                      "Vikas", "Sneha", "Ajay", "Divya", "Ramesh"],

    "City": ["Hyderabad", "Delhi", "Mumbai", "Pune", "Chennai",
             "Delhi", "Hyderabad", "Mumbai", "Pune", "Chennai",
             "Delhi", "Hyderabad", "Mumbai", "Pune", "Chennai",
             "Delhi", "Hyderabad", "Mumbai", "Pune", "Chennai"],

    "Department": ["IT", "HR", "Finance", "Marketing", "IT",
                   "Finance", "HR", "IT", "Marketing", "Finance",
                   "IT", "HR", "Finance", "Marketing", "IT",
                   "Finance", "HR", "IT", "Marketing", "Finance"],

    "Age": [25, 30, 28, 35, 32,
            27, 40, 29, 31, 38,
            26, 33, 36, 41, 24,
            37, 34, 30, 28, 39],

    "Salary": [50000, 60000, 55000, 65000, 70000,
               52000, 75000, 58000, 62000, 68000,
               54000, 71000, 66000, 72000, 51000,
               69000, 73000, 56000, 64000, 74000],

    "Experience_Years": [2, 5, 3, 7, 8,
                         2, 10, 4, 6, 9,
                         2, 7, 8, 11, 1,
                         9, 10, 3, 5, 12],

    "Performance_Score": [85, 90, 88, 92, 95,
                          80, 96, 84, 89, 91,
                          82, 94, 93, 97, 79,
                          90, 98, 83, 87, 96],

    "Joining_Date": ["2021-01-15", "2020-06-20", "2019-03-11",
                     "2018-07-25", "2017-09-14",
                     "2022-04-19", "2016-12-01", "2021-08-10",
                     "2019-05-17", "2015-11-23",
                     "2023-02-14", "2017-01-09", "2016-06-30",
                     "2014-10-05", "2022-09-12",
                     "2015-03-27", "2013-12-18", "2020-01-01",
                     "2018-08-22", "2012-07-07"],

    "Sales": [120000, 150000, 130000, 170000, 200000,
              125000, 210000, 140000, 160000, 190000,
              135000, 205000, 180000, 220000, 115000,
              195000, 230000, 145000, 165000, 240000]
}
import numpy as np
import pandas as pd
df=pd.DataFrame(data)
df

,Order_ID,Customer_Name,City,Department,Age,Salary,Experience_Years,Performance_Score,Joining_Date,Sales
0,2001,Ravi,Hyderabad,IT,25,50000,2,85,2021-01-15,120000
1,2002,Anu,Delhi,HR,30,60000,5,90,2020-06-20,150000
2,2003,Kiran,Mumbai,Finance,28,55000,3,88,2019-03-11,130000
3,2004,Meena,Pune,Marketing,35,65000,7,92,2018-07-25,170000
4,2005,John,Chennai,IT,32,70000,8,95,2017-09-14,200000
5,2006,Priya,Delhi,Finance,27,52000,2,80,2022-04-19,125000
6,2007,Aman,Hyderabad,HR,40,75000,10,96,2016-12-01,210000
7,2008,Sita,Mumbai,IT,29,58000,4,84,2021-08-10,140000
8,2009,Rahul,Pune,Marketing,31,62000,6,89,2019-05-17,160000
9,2010,David,Chennai,Finance,38,68000,9,91,2015-11-23,190000
10,2011,Pooja,Delhi,IT,26,54000,2,82,2023-02-14,135000
11,2012,Arjun,Hyderabad,HR,33,71000,7,94,2017-01-09,205000
12,2013,Kavya,Mumbai,Finance,36,66000,8,93,2016-06-30,180000
13,2014,Mohan,Pune,Marketing,41,72000,11,97,2014-10-05,220000
14,2015,Neha,Chennai,IT,24,51000,1,79,2022-09-12,115000
15,2016,Vikas,Delhi,Finance,37,69000,9,90,2015-03-27,195000
16,2017,Sneha,Hyderabad,HR,34,73000,10,98,2013-12-18,230000
17,2018,Ajay,Mumbai,IT,30,56000,3,83,2020-01-01,145000
18,2019,Divya,Pune,Marketing,28,64000,5,87,2018-08-22,165000
19,2020,Ramesh,Chennai,Finance,39,74000,12,96,2012-07-07,240000

In [ ]:
df.head()

,Order_ID,Customer_Name,City,Department,Age,Salary,Experience_Years,Performance_Score,Joining_Date,Sales
0,2001,Ravi,Hyderabad,IT,25,50000,2,85,2021-01-15,120000
1,2002,Anu,Delhi,HR,30,60000,5,90,2020-06-20,150000
2,2003,Kiran,Mumbai,Finance,28,55000,3,88,2019-03-11,130000
3,2004,Meena,Pune,Marketing,35,65000,7,92,2018-07-25,170000
4,2005,John,Chennai,IT,32,70000,8,95,2017-09-14,200000

In [ ]:
df.dtypes

Order_ID              int64
Customer_Name        object
City                 object
Department           object
Age                   int64
Salary                int64
Experience_Years      int64
Performance_Score     int64
Joining_Date         object
Sales                 int64
dtype: object

In [ ]:
df.columns

Index(['Order_ID', 'Customer_Name', 'City', 'Department', 'Age', 'Salary',
       'Experience_Years', 'Performance_Score', 'Joining_Date', 'Sales'],
      dtype='object')

In [ ]:
df.shape

(20, 10)

In [ ]:
print(df.describe())

         Order_ID        Age        Salary  Experience_Years  \
count    20.00000  20.000000     20.000000         20.000000
mean   2010.50000  32.150000  63250.000000          6.200000
std       5.91608   5.173566   8258.169799          3.381062
min    2001.00000  24.000000  50000.000000          1.000000
25%    2005.75000  28.000000  55750.000000          3.000000
50%    2010.50000  31.500000  64500.000000          6.500000
75%    2015.25000  36.250000  70250.000000          9.000000
max    2020.00000  41.000000  75000.000000         12.000000

       Performance_Score          Sales
count          20.000000      20.000000
mean           89.450000  171250.000000
std             5.817171   38555.325934
min            79.000000  115000.000000
25%            84.750000  138750.000000
50%            90.000000  167500.000000
75%            94.250000  201250.000000
max            98.000000  240000.000000

In [ ]:
df.describe(include='object')

       Customer_Name       City Department Joining_Date
count             20         20         20           20
unique            20          5          4           20
top             Ravi  Hyderabad         IT   2021-01-15
freq               1          4          6            1

In [ ]:
df.describe(include='all')

,Order_ID,Customer_Name,City,Department,Age,Salary,Experience_Years,Performance_Score,Joining_Date,Sales
count,20.00000,20,20,20,20.000000,20.000000,20.000000,20.000000,20,20.000000
unique,NaN,20,5,4,NaN,NaN,NaN,NaN,20,NaN
top,NaN,Ravi,Hyderabad,IT,NaN,NaN,NaN,NaN,2021-01-15,NaN
freq,NaN,1,4,6,NaN,NaN,NaN,NaN,1,NaN
mean,2010.50000,NaN,NaN,NaN,32.150000,63250.000000,6.200000,89.450000,NaN,171250.000000
std,5.91608,NaN,NaN,NaN,5.173566,8258.169799,3.381062,5.817171,NaN,38555.325934
min,2001.00000,NaN,NaN,NaN,24.000000,50000.000000,1.000000,79.000000,NaN,115000.000000
25%,2005.75000,NaN,NaN,NaN,28.000000,55750.000000,3.000000,84.750000,NaN,138750.000000
50%,2010.50000,NaN,NaN,NaN,31.500000,64500.000000,6.500000,90.000000,NaN,167500.000000
75%,2015.25000,NaN,NaN,NaN,36.250000,70250.000000,9.000000,94.250000,NaN,201250.000000
max,2020.00000,NaN,NaN,NaN,41.000000,75000.000000,12.000000,98.000000,NaN,240000.000000

In [ ]:
print(df[['Customer_Name', 'Salary', 'Department']])

   Customer_Name  Salary Department
0           Ravi   50000         IT
1            Anu   60000         HR
2          Kiran   55000    Finance
3          Meena   65000  Marketing
4           John   70000         IT
5          Priya   52000    Finance
6           Aman   75000         HR
7           Sita   58000         IT
8          Rahul   62000  Marketing
9          David   68000    Finance
10         Pooja   54000         IT
11         Arjun   71000         HR
12         Kavya   66000    Finance
13         Mohan   72000  Marketing
14          Neha   51000         IT
15         Vikas   69000    Finance
16         Sneha   73000         HR
17          Ajay   56000         IT
18         Divya   64000  Marketing
19        Ramesh   74000    Finance

In [ ]:
df.dtypes

Order_ID              int64
Customer_Name        object
City                 object
Department           object
Age                   int64
Salary                int64
Experience_Years      int64
Performance_Score     int64
Joining_Date         object
Sales                 int64
dtype: object

In [ ]:
df['Salary']=df['Salary'].astype('Float64')

In [ ]:
df['Salary']=df['Salary'].astype('Int64')

In [ ]:
df['Salary'].apply(lambda x:x>70000)

0     False
1     False
2     False
3     False
4     False
5     False
6      True
7     False
8     False
9     False
10    False
11     True
12    False
13     True
14    False
15    False
16     True
17    False
18    False
19     True
Name: Salary, dtype: bool

In [ ]:
print(df[df['Salary']>70000])

    Order_ID Customer_Name       City Department  Age  Salary  \
6       2007          Aman  Hyderabad         HR   40   75000
11      2012         Arjun  Hyderabad         HR   33   71000
13      2014         Mohan       Pune  Marketing   41   72000
16      2017         Sneha  Hyderabad         HR   34   73000
19      2020        Ramesh    Chennai    Finance   39   74000

    Experience_Years  Performance_Score Joining_Date   Sales
6                 10                 96   2016-12-01  210000
11                 7                 94   2017-01-09  205000
13                11                 97   2014-10-05  220000
16                10                 98   2013-12-18  230000
19                12                 96   2012-07-07  240000

In [ ]:
df.loc[
    (df['Salary'] > 70000) &
    (df['Age'] > 30) &
    (df['Department'] == 'HR'),
    ['Customer_Name', 'Department', 'Age', 'Salary']
]

   Customer_Name Department  Age  Salary
6           Aman         HR   40   75000
11         Arjun         HR   33   71000
16         Sneha         HR   34   73000

0    50000
1    60000
2    55000
3    65000
4    70000
Name: Salary, dtype: Int64

In [ ]:
print(df['Salary'].max())

75000

In [ ]:
print(df['City'])

0     25
1     30
2     28
3     35
4     32
5     27
6     40
7     29
8     31
9     38
10    26
11    33
12    36
13    41
14    24
15    37
16    34
17    30
18    28
19    39
Name: Age, dtype: int64

In [ ]:
df.loc[df['City'].isin(['Hyderabad','Delhi'])]

,Order_ID,Customer_Name,City,Department,Age,Salary,Experience_Years,Performance_Score,Joining_Date,Sales
0,2001,Ravi,Hyderabad,IT,25,50000,2,85,2021-01-15,120000
1,2002,Anu,Delhi,HR,30,60000,5,90,2020-06-20,150000
5,2006,Priya,Delhi,Finance,27,52000,2,80,2022-04-19,125000
6,2007,Aman,Hyderabad,HR,40,75000,10,96,2016-12-01,210000
10,2011,Pooja,Delhi,IT,26,54000,2,82,2023-02-14,135000
11,2012,Arjun,Hyderabad,HR,33,71000,7,94,2017-01-09,205000
15,2016,Vikas,Delhi,Finance,37,69000,9,90,2015-03-27,195000
16,2017,Sneha,Hyderabad,HR,34,73000,10,98,2013-12-18,230000

In [ ]:
df.loc[df['Performance_Score']>90]

,Order_ID,Customer_Name,City,Department,Age,Salary,Experience_Years,Performance_Score,Joining_Date,Sales
3,2004,Meena,Pune,Marketing,35,65000,7,92,2018-07-25,170000
4,2005,John,Chennai,IT,32,70000,8,95,2017-09-14,200000
6,2007,Aman,Hyderabad,HR,40,75000,10,96,2016-12-01,210000
9,2010,David,Chennai,Finance,38,68000,9,91,2015-11-23,190000
11,2012,Arjun,Hyderabad,HR,33,71000,7,94,2017-01-09,205000
12,2013,Kavya,Mumbai,Finance,36,66000,8,93,2016-06-30,180000
13,2014,Mohan,Pune,Marketing,41,72000,11,97,2014-10-05,220000
16,2017,Sneha,Hyderabad,HR,34,73000,10,98,2013-12-18,230000
19,2020,Ramesh,Chennai,Finance,39,74000,12,96,2012-07-07,240000